//
//  Texture2D.h
//  RPG
//
//  Created by Emiliano Berenbaum on 1/22/11.
//  Copyright 2011 MN Inc. All rights reserved.
//

#import <OpenGLES/ES1/gl.h>

// Enumerators for the different pixel formats this class can handle 
typedef enum {
	kTexture2DPixelFormat_Automatic = 0,
	kTexture2DPixelFormat_RGBA8888,
	kTexture2DPixelFormat_RGB565,
	kTexture2DPixelFormat_A8,
} Texture2DPixelFormat;


// The Texture2D class allows any image to be coverted into an OpenGL texture. As 
// input this class takes a UImage instance fo the image to be used as a texture
// and also takes a filter. This filter is used to set  the textures Min and Mag filters
// that are used when you scale a image up and down.
//
// OpenGL textures within OpenGL ES 1.1 are termed power of 2 textures.  That means that their 
// width and height need to be power of 2. This does not mean that the widht and height have 
// to be the  same e.g. 256x256 but they each have to be a power of 2 eg 64x128
//
// Regardles of the size of the image passed in, this class calculates the necessary power of 2
// size for the texture and provides the necessary information for you to then acces the texture
// or any part of the texture
//
// As the texture generated by this class could be larger than the actual image it contains, two 
// variables called maxS and maxT provied the maximum texture coords that define the size of 
// the image with the texture.
//
@interface Texture2D : NSObject {

@private
	GLuint		name;
	CGSize		contentSize;
	NSUInteger	width;
	NSUInteger	height;
	GLfloat		maxS;
	GLfloat		maxT;
	CGSize		textureRatio;		// The ration between pixes and texels (texture coordinates )
	Texture2DPixelFormat pixelFormat;
	
}

@property(nonatomic, readonly) GLuint name;
@property(nonatomic, readonly) CGSize contentSize;
@property(nonatomic, readonly) NSUInteger width;
@property(nonatomic, readonly) NSUInteger height;
@property(nonatomic, readonly) GLfloat maxS;
@property(nonatomic, readonly) GLfloat maxT;
@property(nonatomic, readonly) CGSize textureRatio;
@property(nonatomic, readonly) Texture2DPixelFormat pixelFormat;

// Designated initializer that takes an UIImage and a filter (used for the MIN and MAG settings
// of the texture) and creates an OpenGL texture.
- (id) initWithImage:(UIImage*)aImage filter:(GLenum)aFilter;

@end
